### ISSUE TITLE
handSphereCenter in event.metadata["arm"] has wrong position

### ISSUE THREAD

**Issue by MaekTec** [allenai/manipulathor#11]
handSphereCenter in event.metadata["arm"] has the same value as the position of robot_arm_1_jnt, but robot_arm_4_jnt seems to be the correct handSphereCenter. The position of robot_arm_4_jnt is also used in get_absolute_hand_state() in manipulathor/ithor_arm/ithor_arm_environment.py

https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_environment.py#L267

This is returned by event.metadata["arm"]:
`
{'joints': [{'name': 'robot_arm_1_jnt', 'position': {'x': -0.8999999761581421, 'y': 1.463499903678894, 'z': -0.3290000259876251}, 'rootRelativePosition': {'x': 5.960464477539063e-08, 'y': 0.0, 'z': 2.9802322387695312e-08}, 'rotation': {'x': -0.0, 'y': 1.0000001192092896, 'z': -0.0, 'w': 90.0}, 'rootRelativeRotation': {'x': 0.0, 'y': 1.0000001192092896, 'z': 0.0, 'w': 90.0}, 'localRotation': {'x': 0.0, 'y': 1.0000001192092896, 'z': 0.0, 'w': 90.0}}, {'name': 'robot_arm_2_jnt', 'position': {'x': -0.5834574103355408, 'y': 1.463499903678894, 'z': -0.3290000557899475}, 'rootRelativePosition': {'x': 5.960464477539063e-08, 'y': 0.0, 'z': 0.3165426254272461}, 'rotation': {'x': 0.5968809723854065, 'y': 0.5725464820861816, 'z': -0.5620710253715515, 'w': 123.60325622558594}, 'rootRelativeRotation': {'x': 0.6731582283973694, 'y': 0.189345121383667, 'z': 0.7148473262786865, 'w': 265.23699951171875}, 'localRotation': {'x': 0.6731582283973694, 'y': 0.189345121383667, 'z': 0.7148473262786865, 'w': 265.23699951171875}}, {'name': 'robot_arm_3_jnt', 'position': {'x': -0.5974782109260559, 'y': 1.1478955745697021, 'z': -0.348837673664093}, 'rootRelativePosition': {'x': 0.019837677478790283, 'y': -0.3156043291091919, 'z': 0.30252182483673096}, 'rotation': {'x': 0.30278900265693665, 'y': 0.010122903622686863, 'z': 0.953004002571106, 'w': 180.36859130859375}, 'rootRelativeRotation': {'x': 0.9530039429664612, 'y': 0.010123095475137234, 'z': -0.30278897285461426, 'w': 180.3684844970703}, 'localRotation': {'x': 0.8547145128250122, 'y': 0.5176569223403931, 'z': 0.03865963965654373, 'w': 180.31800842285156}}, {'name': 'robot_arm_4_jnt', 'position': {'x': -0.4145815968513489, 'y': 1.1546282768249512, 'z': -0.09006652235984802}, 'rootRelativePosition': {'x': -0.2389335334300995, 'y': -0.30887162685394287, 'z': 0.485418438911438}, 'rotation': {'x': 0.5722787380218506, 'y': 0.5873619318008423, 'z': 0.5722787380218506, 'w': 119.14329528808594}, 'rootRelativeRotation': {'x': -0.5722788572311401, 'y': 0.5873619318008423, 'z': 0.5722787976264954, 'w': 119.14328002929688}, 'localRotation': {'x': -0.14109723269939423, 'y': -0.7303881049156189, 'z': 0.6682999134063721, 'w': 140.92092895507812}}], 'heldObjects': [], 'pickupableObjects': [], 'handSphereCenter': {'x': -0.8999999761581421, 'y': 1.463499903678894, 'z': -0.3290000259876251}, 'handSphereRadius': 0.11999999731779099}
`

**Comment by ehsanik** [comment]
Hi, 

We had fixed this issue on the newer builds. You can update your ai2thor to the latest version and use the build number "a84dd29471ec2201f583de00257d84fac1a03de2" to see the effects. I'll update the build we use in this repo in a bit as well. Thanks for pointing it out.

**Comment by MaekTec** [comment]
Thanks for the quick answer! With the new build it returns the correct value.
