### ISSUE TITLE
Can not setup the training, evaluation

### ISSUE THREAD

**Issue by trangntt-for-student** [allenai/manipulathor#19]
Hello, first of all, I want to tell you that I really enjoy and appreciate your project as well as what was presented in your paper. However, when running your code, I have some troubles, it seems that:
`allenact manipulathor_baselines/armpointnav_baselines/experiments/ithor/<EXPERIMENT-NAME> -o experiment_output -s 1`
and
`allenact manipulathor_baselines/armpointnav_baselines/experiments/ithor/<EXPERIMENT-NAME> -o test_out -s 1 -t test -c <WEIGHT-ADDRESS>`
can not work properly anymore, could you tell me how to fix this, please? Thank you in advance!
![image](https://user-images.githubusercontent.com/71226210/177269070-fbf132eb-3589-4913-b2c6-564d7e5870b7.png)
![image](https://user-images.githubusercontent.com/71226210/177269254-0cfc2258-26f9-4047-af66-b51d220c389f.png)

**Comment by trangntt-for-student** [comment]
> 

Well, I managed to solve this issue, the solution is simple:
`allenact armpointnav_depth -b projects/manipulathor_baselines/armpointnav_baselines/experiments/ithor -o experiment_output -s 1`
and
`allenact armpointnav_depth -b projects/manipulathor_baselines/armpointnav_baselines/experiments/ithor -o test_out -s 1 --eval -c /content/manipulathor/pretrained_models/saved_checkpoints/depth_armpointnav.pt`

**Comment by ehsanik** [comment]
Awesome :) Glad you found a solution.
