### ISSUE TITLE
Magic number is wrong: 542

### ISSUE THREAD

**Issue by zhangfuyang** [allenai/manipulathor#3]
Hi, really interesting work!

My machine: ubuntu20 + 2 nvidia 1080 GPUs + CUDA 11.2. I have run this script (https://github.com/allenai/allenact/blob/main/scripts/startx.py) to start x-display.

I got an exception when I was evaluating the pre-trained model (rgbdepth_armpointnav.pt). Below is the screenshot

![image](https://user-images.githubusercontent.com/26685632/116444758-ebd97080-a809-11eb-8aa2-ff637d7ecaa7.png)

I wonder what is that exception? 

I kept running while ignoring the exception periodically popping up. I can still get the metrics_test*.json in experiment_output. But there is nothing in experiment_output/checkpoints (except empty folders) and the tf log file in experiment_output/tb contains nothing. Is that normal? Also, wondering if the code will generate some video clips or images during the evaluating?

BTW, It would be great if there is a similar example.py (https://github.com/allenai/ai2thor-rearrangement/blob/main/example.py) to let people play around with the environment. :) 

Thank you!
Fuyang Zhang

**Comment by ekolve** [comment]
Can you confirm that you have a Xorg server running? Can you also try running `glxgears` (installable from the mesa-utils package).  Your log indicates that the Player is attempting to use the Vulkan driver, which may mean that the OpenGL driver is not available.

**Comment by ehsanik** [comment]
Thank you for the suggestion. I just added an example Jupiter notebook [here](https://github.com/allenai/manipulathor/blob/main/scripts/example_notebook.ipynb). Please give it a try and see if it works. If it doesn't work, the problem might be with your server as Eric suggested.

**Comment by zhangfuyang** [comment]
@ekolve Thank you for the help! @ehsanik Thank you for the example, I will try it as soon as I solved my server issue.

Just a quick check if this running situation is as expected.  I followed this [link](https://github.com/allenai/ai2thor-rearrangement/issues/7) to start Xorg for both two gpus. The current log output is like this:
![image](https://user-images.githubusercontent.com/26685632/116470907-e0497200-a828-11eb-9bc2-ac623401b08a.png)![image](https://user-images.githubusercontent.com/26685632/116472276-89449c80-a82a-11eb-861b-f3a24e02162f.png)


Is that normal?

Also, I still saw an error message at the beginning, "error: XDG_RUNTIME_DIR not set in the environment.". Does that mean my server is still not set correctly? I googled it, looks like I need to specify the display variable before running the main.py? Do you have any suggestions? Any comments may help.

BTW, what is the proper output? will it visualize some rooms during evaluating?

**Comment by zhangfuyang** [comment]
@ehsanik Thanks again for the example. I can run it successfully! But I just find there are no "drop" or "open" actions. And in the paper, it's also not mentioned these actions in the experiments section. Does that mean we don't need to consider the cases that need to manipulate other objects before grasping the target?

**Comment by ehsanik** [comment]
I just added the drop action. However, we did not use the "open" action. As it is mentioned in the paper manipulating objects inside a closed container is outside the scope of this project.
