### ISSUE TITLE
how to set the third-person perspective？

### ISSUE THREAD

**Issue by yyf17** [allenai/manipulathor#7]
Thank you for your very beautiful work. May I ask how to set the third-person perspective

**Comment by mattdeitke** [comment]
Hey @yyf17,

This can be done in AI2-THOR by adding a `ThirdPartyCamera`. For example:

```python
from ai2thor.controller import Controller
controller = Controller()
event = controller.step(
    action="AddThirdPartyCamera",
    position=dict(x=0, y=3, z=0)
    rotation=dict(x=90, y=0, z=0)
)
rgb_image = event.third_party_camera_frames[0]

```

See the documentation [here](https://ai2thor.allenai.org/ithor/documentation/environment-state/#add-camera) for more information.

**Comment by yyf17** [comment]
@mattdeitke Thank you for your patient guidance. I got a picture of the robotic arm, but the viewing angle is not right. 
![image](https://user-images.githubusercontent.com/34536352/125181579-a3422880-e238-11eb-8800-56e5c056bbc2.png)

My code is as follows:
```
%matplotlib inline
import matplotlib.pyplot as plt
from ai2thor.controller import Controller

screen_width = 900
controller = Controller(
    agentMode="arm",
    massThreshold=None,
    scene="FloorPlan203",
    visibilityDistance=1.5,
    agentControllerType='mid-level',
    gridSize=0.25,
    renderDepthImage=True,
    renderInstanceSegmentation=False,
    width=screen_width,
    height=screen_width,
    fieldOfView=60
)

event = controller.step(
    action="AddThirdPartyCamera",
    position=dict(x=-3.0, y=1.5820531845092773, z=2.75),
    rotation=dict(x=90, y=0, z=0),
)
rgb_image = event.third_party_camera_frames[0]
plt.imshow(rgb_image)
```
The effect I want to get is as follows:
![image](https://user-images.githubusercontent.com/34536352/125181593-c66cd800-e238-11eb-8645-b072b1c87013.png)
How can I do this？
Would you give me some further suggestions?

**Comment by yyf17** [comment]
@mattdeitke My AI2-THOR Version is 3.0.0.

**Comment by mattdeitke** [comment]
Hi @yyf17, your code looks correct. I would play around with the camera position and rotation for it to look more like what is show in the video.

For instance, a rotation with `x=90` is for a top down view, so it may be better to use `x=0` here. Moreover, you may want to rotate `y` to an increment like `y=45` so that the camera is slightly tilted, like so:
```python
event = controller.step(
    action="AddThirdPartyCamera",
    position=dict(x=-3.0, y=0.5, z=1.55),
    rotation=dict(x=0, y=45, z=0),
)
```
You'll probably also need to change the `x` and `z` position, so that it is not on top of the camera.

But, what you have is correct, just requires playing around with the camera parameters :)

**Comment by yyf17** [comment]
@mattdeitke Thank you very much.
