### ISSUE TITLE
Avoid collisions with the table

### ISSUE THREAD

**Issue by marleyshan21** [allenai/manipulathor#8]
Hi, We are trying to implement object manipulation - A pickup and release for a series of different objects on a particular table using the manipulathor arm.
The goal coordinates are given manually.
While attempting to pick up certain objects, the arm is colliding with the table and hence moving it.
We want the arm to plan in such a way that it doesn't collide with the table. How do we prevent this collision?
1. Is there any kind of feedback that we can receive prior to the arm's motion, warning us of the possibility of a collision, so that we can iteratively rotate or modify the joints to avoid a collision with the table.
or
2. Any other alternative approach that we should consider to achieve this abstraction from collision avoidance?"

Our main objective is to work on the pick and place of objects without worrying much about collision handling. 
We made it work by manually handling the arm base height and the Relative Elbow Rotation. However, we are looking to automate this task (integrate it to the agent itself) where the arm does not collide with obstacles while on its way to pick or release objects and also generalise this over different situations. 

Ai2thor version -  3.3.4

![table_collision](https://user-images.githubusercontent.com/43117628/126026165-cf62c9be-e734-40ef-8d3d-acfa5eb5dafb.gif)

**Comment by ehsanik** [comment]
Hi,

If you look at Success Rate without Disturbance Metric (SRwD) [here](https://github.com/allenai/manipulathor/blob/323e2deed4017cb2ee8bbffa8de07e43f5c13d22/ithor_arm/ithor_arm_tasks.py#L205), you can see our implementation of how to detect if we have made any unwanted moves while performing the tasks, which is basically moving any object other than the target object. While we didn't directly use this during training, it can be used to introduce additional reward functions for encouraging the agent to avoid these collisions. 

We have shown in the paper that without this additional reward we can successfully finish an episode without additional collisions in 39.4% of the time.
